### ISSUE TITLE
save_all logic may be flawed

### ISSUE THREAD

**Issue by onelivesleft** [focus-editor/focus#121]
Updating my fork I see the code for save_all is 

```
save_all :: (editor: *Editor, buffer: *Buffer) {
    new_edit_group(buffer, editor);

    for * b, b_id : open_buffers {
        if !b.modified continue;
        save_buffer_to_disk(b, b_id);
    }
}
```

I feel the logic should be: 
```
save_all :: (editor : *Editor = null, buffer : *Buffer = null) {
    for * b, b_id : open_buffers {
        if !b.modified continue;

        if b.num_editors_open {
            for * e: open_editors {
                if e.buffer_id == b_id {
                    new_edit_group(b, e);
                    break;
                }
            }
        }

        save_buffer_to_disk(b, b_id);
    }
}
```

No?  If so, my version still isn't quite right if the buffer is open in two editors, but the way new_edit_group works it looks like it definitely shouldn't be called twice on the same buffer (hence the break).

**Comment by focus-editor** [comment]
I'm not sure what problem you're referring to here. That we don't call `new_edit_group` for every open editor and buffer? 

`new_edit_group` isn't really related to saving, it's just called here as hitting save is a good spot to mark a new edit group, if I remember correctly.

Also, it's safe to call it as often as you need, because if the buffer has no edits (and it won't after the first call) it will just do an early return.
