### ISSUE TITLE
[Feature Request] `C/C++` #if x block

### ISSUE THREAD

**Issue by vulcan-dev** [focus-editor/focus#306]
It would be nice if we could have blocks such as these grayed out:
```c
#if 0
    // Some magical things here
#endif
```

I think it should only support `#if 0` and `#if 1` to keep it simple.

**Comment by focus-editor** [comment]
I've tried to implement it and realised it will be confusing if we don't handle all cases, so at this time it's best not to implement it at all.

For example, we could handle `#if 0` (however it's quite expensive due to the way we do highlighting now), but then we'd have to handle the case

```
#if 1
    ...
#else
    // this should be greyed out
#endif
```

So if we were to handle all those cases, it would put a strain on the tokenizer, and if we didn't people would complain it doesn't work in their case. So for now we just won't do it at all.
