### ISSUE TITLE
Bindings using only Ctrl are not working

### ISSUE THREAD

**Issue by tschlink** [focus-editor/focus#343]
**Describe the bug**
I tried adding a few bindings like `Ctrl-P` and `Ctrl-N` to move a line up or down, but none of them are working.
It seems to affect more types of bindings, I tried `Ctrl-D` to delete a line, which also didn't work. I made sure there were now conflicts with existing bindings.
The viewport scrolling functions involving Ctrl and default bindings like `Ctrl-Enter` are working fine however.

**To Reproduce**
1. Open Global Config
2. Add a binding using only Ctrl, e.g. `Ctrl-P  move_up`
3. Save config
4. Try using the binding

**Expected behavior**
Ctrl can be used as a modifier on it's own for arbitrary keybindings.

 - OS: MacOS Sonoma (14.4.1)
 - Focus Version: 0.3.4-3

**Additional context**
I've attached my current global config file, the bindings are under `#Basic Movement`
[global.focus-config.txt](https://github.com/focus-editor/focus/files/15022831/global.focus-config.txt)

**Comment by focus-editor** [comment]
I can reproduce the issue, thanks for the report. This is due to the way the input is handled in the jai input module, which is by no means finished.
We'll need to look into it, which is not trivial, so it might be a while. Please can you use other key combos in the mean time.

Unfortunately the macOS version of the editor has the most issues at the moment.

**Comment by ileonte** [comment]
This issue should now be fixed, please try this "nightly" build: https://ileonte.dev/focus-builds/macOS/dev/Focus-0.3.4-9dab567-Intel.dmg
