### ISSUE TITLE
Unable to save file

### ISSUE THREAD

**Issue by Quertin** [focus-editor/focus#66]
Unable to save file created with ctrl-n by pressing ctrl-s or the save dialog when quitting focus.

Focus only outputs "name = 'filename" to console when pressing ctrl-s and no errors,
the "save" button in the quit focus dialog does nothing only "cancel" and "don't save" do anything.
I also didn't find a way to determine which folder it tries to write to.

I tried default config file and running focus as sudo.

Linux Mint 21.1 Cinnamon with 5.19.0-43-generic Kernel.
focus-linux Version 0.1.10.

![b](https://github.com/focus-editor/focus/assets/136612013/4a6e4097-0093-46f3-85c5-3b71066e85c3)

**Comment by focus-editor** [comment]
On Linux unfortunately this is not implemented yet. There will be a custom file save dialog since there isn't any standard file explorer like on Windows or macOS that we could use.

**Comment by ivan-cx** [comment]
I'd like to look into that, maybe implement some very basic save dialog, if there are no objections :-)

**Comment by focus-editor** [comment]
@ivan-cx sure if you want to take a stab, please do. But if you want it merged it may require some back and forth to make sure the UI is in alignment with the editor's philosophy. Just saying because apparently some people were upset when their pull requests weren't merged immediately.

**Comment by ivan-cx** [comment]
@focus-editor thanks, good to know! That's why I want to start with something minimal :-)

**Comment by ivan-cx** [comment]
@focus-editor so, I got stuck on this (and I think it would be useful for other implementation attempts in the future): 

on Windows you use **GetOpenFileNameW** inside **platform_get_save_file_name**, which (if I understand correctly) blocks the main loop and render, and returns the target path "immediately" to our program. Please correct me, if I'm mistaken here.

So, with such architecture we would be forced to use some blocking OS-specific UI (since our main loop is blocked and we can't render our own UI), which... could be an option, but who would guarantee that each OS has such special UI? 

I would try to implement single solution for all platforms with an option to rollback to original way on Windows. I'm not expecting to merge this experiment to the mainline, but maybe it would be useful for future attempts to solve this.

**Comment by focus-editor** [comment]
Yes it's not a trivial piece of work. You'd need to implement another widget similar to the open file dialog and activate it instead of calling the standard platform dialog. 

We'd still like to keep the possibility to use the standard dialog on Windows or macOS because some users prefer that, so we'd need a boolean flag in the config - something like `use_custom_file_save_dialog: true`

**Comment by ileonte** [comment]
This is fixed on `main`. People that don't have access to the Jai beta can use the nightly builds until the next official release.
